services:

  database:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql_container
    command: >
      sh -c "
      mysql_install_db &&
      mysqld --init-file=/docker-entrypoint-initdb.d/database_scheme.sql --default-authentication-plugin=mysql_native_password
      "
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    volumes:
      - ./database_scheme.sql:/docker-entrypoint-initdb.d/database_scheme.sql
    ports:
      - "3306:3306"
    restart: always

  process-files:
    image: process-files
    container_name: process-files
    build: images/process-files
    command: ["python", "process-files.py"]
    volumes:
      - ./data:/data

  summarize-tables:
    image: summarize-tables
    container_name: summarize-tables
    build: images/summarize-tables
    command: ["python", "summarize-tables.py"]
    volumes:
      - ./data:/data
